// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/_env.ts
function getEnv(name) {
  const d = globalThis.Deno;
  const v = d?.env?.get?.(name) ?? (typeof process !== "undefined" ? process.env?.[name] : void 0);
  return v ?? "";
}

// src/lib/mcp/tools/list-clients.ts
function supabaseForUser(ctx) {
  return createClient(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY") || getEnv("SUPABASE_ANON_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Lijst klanten",
  description: "Geef alle klanten (boekhoudkantoor) waar de ingelogde gebruiker toegang toe heeft.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("clients").select("id, name, organization_id").order("name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-purchase-invoices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY") || getEnv("SUPABASE_ANON_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_purchase_invoices_default = defineTool2({
  name: "list_open_purchase_invoices",
  title: "Openstaande inkoopfacturen",
  description: "Geef inkoopfacturen met status 'te_controleren' voor de ingelogde gebruiker, optioneel gefilterd op klant.",
  inputSchema: {
    client_id: z.string().uuid().optional().describe("Optioneel klant-id om op te filteren"),
    limit: z.number().int().min(1).max(200).optional().describe("Maximaal aantal (standaard 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("purchase_invoices").select("id, invoice_number, invoice_date, amount_incl, amount_excl, btw_amount, status, client_id, supplier_name").eq("status", "te_controleren").order("invoice_date", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-sales-invoices.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY") || getEnv("SUPABASE_ANON_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_open_sales_invoices_default = defineTool3({
  name: "list_open_sales_invoices",
  title: "Openstaande verkoopfacturen",
  description: "Geef verkoopfacturen met een openstaand bedrag (remaining_amount > 0), optioneel gefilterd op klant.",
  inputSchema: {
    client_id: z2.string().uuid().optional().describe("Optioneel klant-id om op te filteren"),
    limit: z2.number().int().min(1).max(200).optional().describe("Maximaal aantal (standaard 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("sales_invoices").select("id, invoice_number, invoice_date, due_date, customer_name, amount_incl, remaining_amount, status, client_id").gt("remaining_amount", 0).order("invoice_date", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-unmatched-bank-transactions.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(getEnv("SUPABASE_URL"), getEnv("SUPABASE_PUBLISHABLE_KEY") || getEnv("SUPABASE_ANON_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_unmatched_bank_transactions_default = defineTool4({
  name: "list_unmatched_bank_transactions",
  title: "Niet-gematchte banktransacties",
  description: "Geef banktransacties met status 'niet_gematcht' voor de ingelogde gebruiker, optioneel gefilterd op klant.",
  inputSchema: {
    client_id: z3.string().uuid().optional().describe("Optioneel klant-id om op te filteren"),
    limit: z3.number().int().min(1).max(200).optional().describe("Maximaal aantal (standaard 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("bank_transactions").select("id, transaction_date, amount, description, counter_account, reference, status, client_id").eq("status", "niet_gematcht").order("transaction_date", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "alxlbdhpbwlehbdbfejw";
var mcp_default = defineMcp({
  name: "boekassist-mcp",
  title: "BoekAssist MCP",
  version: "0.1.0",
  instructions: "Tools voor BoekAssist \u2014 een boekhoudapp voor Nederlandse boekhoudkantoren. Gebruik `list_clients` om klanten op te halen, en de overige tools voor openstaande inkoop-/verkoopfacturen en niet-gematchte banktransacties. Alle tools werken binnen de rechten (RLS) van de ingelogde gebruiker.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    list_open_purchase_invoices_default,
    list_open_sales_invoices_default,
    list_unmatched_bank_transactions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
